import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { access, copyFile, cp, readFile, writeFile } from "fs/promises";
import path from "node:path";
import { patchPptxRendererSource } from "./scripts/lib/patch-pptx-renderer.mjs";
import { patchReactDomScriptCreation } from "./scripts/lib/strip-react-dom-script.mjs";
import {
	createDocxEditorAliases,
	resolveDocxEditorPackagesRoot,
} from "./scripts/lib/docx-editor-aliases.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Copy the build artifacts into the running Obsidian plugin folder so changes
// take effect on reload. Resolves to the vault plugin dir when this repo lives
// inside the vault (../../.obsidian/plugins/<id>), and is skipped silently when
// that folder is absent (e.g. CI or a clone outside the vault). Override with
// OBSIDIAN_PLUGIN_DIR.
const vaultPluginDir =
	process.env.OBSIDIAN_PLUGIN_DIR
	|| path.resolve("../../.obsidian/plugins/native-powerpoint-doc-editor");
const filesToDeploy = ["main.js", "styles.css", "manifest.json"];
const dirsToDeploy = ["locales", "ai"];
const projectRoot = path.resolve(".");
const docxEditorAliases = await createDocxEditorAliases(
	resolveDocxEditorPackagesRoot(projectRoot),
);

const deployToVaultPlugin = {
	name: "deploy-to-vault-plugin",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;

			try {
				await access(vaultPluginDir);
			} catch {
				return;
			}

			await Promise.all(
				filesToDeploy.map(async (file) => {
					try {
						await copyFile(path.resolve(file), path.join(vaultPluginDir, file));
					} catch (error) {
						console.warn(`[deploy] could not copy ${file}: ${error.message}`);
					}
				})
			);

			await Promise.all(
				dirsToDeploy.map(async (dir) => {
					try {
						await cp(path.resolve(dir), path.join(vaultPluginDir, dir), { recursive: true });
					} catch (error) {
						console.warn(`[deploy] could not copy ${dir}: ${error.message}`);
					}
				})
			);

			// Write a fresh build stamp the in-app dev hot-reload watcher polls.
			// Content-based detection is more reliable than file mtime across
			// platforms/adapters. Only meaningful when a `.hotreload` marker exists.
			try {
				await writeFile(
					path.join(vaultPluginDir, ".build-stamp"),
					`${Date.now()}\n`,
				);
			} catch {
				// Non-fatal: stamp is dev convenience only.
			}

			console.log(`[deploy] synced ${filesToDeploy.join(", ")}, ${dirsToDeploy.join(", ")} -> ${vaultPluginDir}`);
		});
	}
};

const inlinePptxSvgWasmPlugin = {
	name: "inline-pptx-svg-wasm",
	setup(build) {
		build.onLoad({ filter: /pptx-renderer\.js$/ }, async (args) => {
			const normalizedPath = args.path.replace(/\\/g, "/");
			if (!normalizedPath.endsWith("/node_modules/pptx-svg/dist/pptx-renderer.js")) {
				return undefined;
			}

			const source = await readFile(args.path, "utf8");
			const contents = patchPptxRendererSource(source);

			return { contents, loader: "js" };
		});
	}
};

const stripReactDomScriptPlugin = {
	name: "strip-react-dom-script",
	setup(build) {
		build.onLoad({ filter: /react-dom-client\.(production|development)\.js$/ }, async (args) => {
			const source = await readFile(args.path, "utf8");
			return {
				contents: patchReactDomScriptCreation(source, args.path),
				loader: "js",
			};
		});
	}
};

const stripDocxEditorCssSideEffectImports = {
	name: "strip-docx-editor-css-side-effect-imports",
	setup(build) {
		build.onLoad({ filter: /docx-editor[/\\]packages[/\\]react[/\\]dist[/\\]index\.mjs$/ }, async (args) => {
			const normalizedPath = args.path.replace(/\\/g, "/");
			if (!normalizedPath.endsWith("/docx-editor/packages/react/dist/index.mjs")) {
				return undefined;
			}

			const source = await readFile(args.path, "utf8");
			const contents = source
				.replace(/import['"]prosemirror-view\/style\/prosemirror\.css['"];/g, "")
				.replace(/import['"]@(?:eigenpal|npde)\/docx-editor-core\/prosemirror\/editor\.css['"];/g, "");

			return { contents, loader: "js" };
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: "src/main.ts",
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	// The pure-JS PPTX engine fallback (src/powerpoint/backend/pptxJsEngine.mjs) uses BigInt
	// literals. It only runs on Chromium that lacks WebAssembly GC (≈111–118), all
	// of which support BigInt natively (Chrome 67+), so don't down-level or warn.
	supported: { bigint: true },
	alias: {
		...docxEditorAliases,
		"jszip": "./node_modules/jszip/lib/index.js",
		"immediate": "./src/shims/immediate.cjs",
		"readable-stream": "./node_modules/jszip/lib/readable-stream-browser.js",
		"setimmediate": "./src/shims/setimmediate.ts",
		"stream": "./src/shims/stream.cjs",
	},
	loader: {
		".css": "text",
		".json": "json",
		".wasm": "binary",
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [stripReactDomScriptPlugin, stripDocxEditorCssSideEffectImports, inlinePptxSvgWasmPlugin, deployToVaultPlugin],
	outdir: ".",
	entryNames: "[name]",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
